export type ArticleSeed = {
  title: string;
  slug: string;
  excerpt: string;
  content: string[];
  categorySlug: string;
  countryIso2: string;
  tagSlugs: string[];
  daysAgo: number;
  viewCount: number;
  bookmarkCount: number;
  commentCount: number;
  isFeatured: boolean;
  coverSeed: string;
  coverUrl?: string;
};

export const articles: ArticleSeed[] = [
  {
    title:
      "Alice in Borderland Season 2 Ending Explained: What The Joker Card Really Means",
    slug: "alice-in-borderland-season-2-ending-explained-joker-card",
    excerpt:
      "Did Arisu and Usagi truly return to the real world, or was the hospital just another stage? Here is the full breakdown of the meteorite, the purgatory theory, and the chilling Joker card reveal.",
    content: [
      "<p>Few television finales in recent memory have delivered as much emotional whiplash as the Season 2 climax of Netflix’s survival thriller <strong>Alice in Borderland</strong> (今際の国のアリス). After two seasons of brutal psychological death games, betrayals, and heartbreaking sacrifices, Ryōhei Arisu and Yuzuha Usagi finally face the last remaining face card: the enigmatic Queen of Hearts, Mira Kano.</p>",
      "<p>Yet, when the final game concluded, viewers were not greeted with a straightforward victory parade. Instead, the series unraveled a sequence of philosophical mind games, a devastating real-world catastrophe, and a chilling final camera tilt towards a solitary <strong>Joker card</strong> that left millions asking: <em>Did they actually wake up in the real world, or is the game far from over?</em></p>",
      "<h2>The Psychological Gauntlet: Mira Kano's False Realities</h2>",
      "<p>Before understanding the hospital ending, we must dissect the Queen of Hearts game—a seemingly innocuous match of croquet. Unlike the visceral combat against the King of Spades or the brutal chemical traps of the King of Diamonds, Mira’s game was entirely psychological.</p>",
      "<p>Mira subjects Arisu to a devastating series of hallucinations and gaslighting narratives. First, she claims the Borderland is an advanced virtual reality simulation set centuries in the future. When Arisu rejects this, she pivots to an even crueler explanation: that Arisu suffered a psychotic break after his best friends Karube and Chōta were struck by a car in Shibuya, and that the entire Borderland was merely a coping delusion created in a psychiatric facility.</p>",
      "<p>This psychological assault pushes Arisu to the brink of complete surrender. It is only Usagi’s unconditional devotion—slitting her own wrist to force Arisu back into conscious reality—that breaks Mira's hypnotic hold. By merely completing three rounds of croquet without forfeiting, Arisu clears the game, signaling the complete defeat of every face-card master.</p>",
      "<h2>The Ultimate Choice: Acceptance or Rejection of Residency</h2>",
      "<p>Upon clearing the Queen of Hearts, all surviving players receive a broadcast inquiry: <em>Do you wish to accept permanent residency in this country, or do you decline?</em></p>",
      "<p>Those who choose to stay—such as the mercenary Banda and the obsessive serial killer Yaba—become the new generation of Game Masters and Face Cards for future cycles. Conversely, Arisu, Usagi, Kuina, Chishiya, Aguni, Akane Heiya, and Niragi all reject the offer. Their refusal initiates the deconstruction of the Borderlands and triggers their return.</p>",
      "<h2>The Meteorite Revelation: What Was the Borderland?</h2>",
      "<p>The finale abruptly transitions to a bustling, sunlit Tokyo hospital ward. Here, the fundamental nature of the Borderlands is finally revealed through news broadcasts and medical examinations.</p>",
      "<p>The entire alternate Tokyo was not a parallel dimension, an alien simulation, or a virtual game. It was <strong>a shared near-death limbo (purgatory)</strong>. During the opening moments of Episode 1 of Season 1, when Arisu and his friends saw mysterious fireworks over Shibuya crossing, those fireworks were in fact fragments of a massive meteorite exploding in the atmosphere above Tokyo.</p>",
      "<p>Everyone caught in the blast radius suffered severe physical trauma. For those whose hearts stopped, their consciousness was plunged into the Borderlands—a psychological crucible where their will to live determined their survival. In the real world, only <strong>one minute</strong> of cardiac arrest elapsed, yet in the Borderlands, that minute felt like weeks of grueling trials. Those who died in the games succumbed to their injuries on the hospital operating tables; those who fought to survive were resuscitated.</p>",
      "<h2>The Amnesia and the Reconnection</h2>",
      "<p>Upon waking up in the hospital, none of the survivors retain conscious memory of the death games or the bonds they forged. Chishiya reflects peacefully from his hospital bed, Kuina reunites tearfully with her estranged family, and Aguni survives despite his catastrophic wounds.</p>",
      "<p>The most poignant moment arrives when Arisu and Usagi meet by a hospital vending machine. Neither consciously recognizes the other, yet an inexplicable emotional resonance passes between them. When Arisu asks if they have met before, Usagi smiles, and the two agree to walk together in the hospital courtyard—proving that while conscious memories were wiped, the soul's emotional growth remains intact.</p>",
      "<h2>The Joker Card: What Does the Final Shot Mean?</h2>",
      "<p>Just as viewers prepare for a tidy, comforting conclusion, the camera pans across the hospital grounds and focuses on a table where a deck of playing cards is scattered by the wind. Every card blows away until only one remains centered on the table: <strong>The Joker</strong>.</p>",
      "<p>In the original manga created by Haro Aso, the Joker represents <strong>Charon</strong>—the mythological Ferryman of the Underworld who transports souls between life and death. The Joker is neither an adversary nor an ally; he is the neutral warden of the Borderlands.</p>",
      "<p>However, in the context of the Netflix adaptation, the Joker card introduces an ominous cliffhanger that could mean one of two possibilities:</p>",
      "<ul>",
      "<li><strong>Theory A (The Illusion of Awakening):</strong> The hospital itself is the ultimate Stage 3 game masterminded by the Joker. Just as Mira attempted to trap Arisu in a psychiatric illusion, the Joker has placed the survivors into a placid, tranquil simulation where they let down their guard.</li>",
      "<li><strong>Theory B (The Inevitability of the Ferryman):</strong> The survivors truly returned to reality, but the Joker card serves as a memento mori—a stark reminder that life itself is unpredictable, fragile, and governed by the hand of fate.</li>",
      "</ul>",
      "<h2>What Awaits in Season 3?</h2>",
      "<p>With Netflix officially renewing <em>Alice in Borderland</em> for Season 3 under director Shinsuke Sato, the Joker card is primed to serve as the narrative catalyst. Whether adapting the <em>Alice in Borderland: Retry</em> manga—where an older Arisu is forced back into the Borderlands following another life-threatening accident—or venturing into completely original territory, one truth is undeniable: the dealer has not laid down the final hand.</p>",
    ],
    categorySlug: "ending-explained",
    countryIso2: "JP",
    tagSlugs: [
      "ending-explained",
      "psychological-thriller",
      "netflix",
      "plot-twist",
    ],
    daysAgo: 0,
    viewCount: 14200,
    bookmarkCount: 820,
    commentCount: 95,
    isFeatured: true,
    coverSeed: "alice-borderland",
    coverUrl: "/images/alice-in-borderland.jpg",
  },
  {
    title: "World Leaders Convene for Global Climate Summit",
    slug: "world-leaders-convene-global-climate-summit",
    excerpt:
      "Delegations from over a hundred nations gathered to negotiate new emissions targets and financing for climate adaptation.",
    content: [
      "Delegations from more than a hundred countries opened a multi-day summit aimed at accelerating global climate commitments, with negotiators focused on emissions targets, adaptation financing, and support for vulnerable regions.",
      "Officials said early discussions centered on a proposed fund to help developing nations transition away from fossil fuels while maintaining economic growth. Several ministers described the talks as constructive but acknowledged that gaps remain on financing timelines.",
      "Observers noted that this year's summit carries added urgency following a string of extreme weather events across multiple continents. A final communique is expected before the summit concludes later this week.",
    ],
    categorySlug: "world",
    countryIso2: "FR",
    tagSlugs: ["climate-change", "diplomacy"],
    daysAgo: 1,
    viewCount: 5400,
    bookmarkCount: 210,
    commentCount: 34,
    isFeatured: true,
    coverSeed: "climate-summit",
  },
  {
    title: "Global Markets Rally as Inflation Data Cools",
    slug: "global-markets-rally-inflation-cools",
    excerpt:
      "Equity markets posted broad gains after new figures showed inflation easing faster than economists had expected.",
    content: [
      "Stock indexes rose broadly after fresh inflation data came in below analyst expectations, fueling investor hopes that central banks may ease their tightening stance in the coming months.",
      "Trading desks reported strong gains in technology and consumer discretionary shares, sectors that are typically the most sensitive to interest rate expectations. Bond yields also retreated as the data was released.",
      "Analysts cautioned that a single report does not guarantee a sustained trend, noting that policymakers are likely to wait for several more months of data before shifting course.",
    ],
    categorySlug: "business",
    countryIso2: "US",
    tagSlugs: ["markets", "global-trade"],
    daysAgo: 2,
    viewCount: 4200,
    bookmarkCount: 150,
    commentCount: 22,
    isFeatured: false,
    coverSeed: "markets-rally",
  },
  {
    title: "Tech Giant Unveils Next-Generation AI Assistant",
    slug: "tech-giant-unveils-next-gen-ai-assistant",
    excerpt:
      "The new assistant introduces real-time reasoning and multimodal capabilities aimed at enterprise and consumer users alike.",
    content: [
      "A leading technology company unveiled its latest AI assistant, showcasing improved reasoning, faster response times, and the ability to process text, images, and audio within a single conversation.",
      "Company executives said the release reflects years of research into more efficient model architectures, and emphasized new safety tooling designed to reduce inaccurate or harmful outputs.",
      "The assistant will roll out first to enterprise customers before a broader consumer release later this year. Competitors are expected to respond with their own updates in the coming weeks.",
    ],
    categorySlug: "technology",
    countryIso2: "US",
    tagSlugs: ["artificial-intelligence", "startups"],
    daysAgo: 1,
    viewCount: 8900,
    bookmarkCount: 430,
    commentCount: 88,
    isFeatured: true,
    coverSeed: "ai-assistant",
  },
  {
    title: "Researchers Unveil Breakthrough in Battery Technology",
    slug: "researchers-breakthrough-battery-technology",
    excerpt:
      "A new solid-state design promises longer range and faster charging for electric vehicles and grid storage.",
    content: [
      "A team of materials scientists announced a new solid-state battery design that significantly increases energy density while reducing charging times compared to conventional lithium-ion cells.",
      "The research, published this week, demonstrated stable performance across hundreds of charge cycles in laboratory conditions. Industry partners are already evaluating the technology for potential commercial use.",
      "Experts caution that scaling laboratory results to mass production typically takes several years, but described the findings as a meaningful step toward more efficient energy storage.",
    ],
    categorySlug: "science",
    countryIso2: "JP",
    tagSlugs: ["renewable-energy"],
    daysAgo: 3,
    viewCount: 3100,
    bookmarkCount: 120,
    commentCount: 15,
    isFeatured: false,
    coverSeed: "battery-tech",
  },
  {
    title: "New Study Links Sleep Patterns to Long-Term Heart Health",
    slug: "study-links-sleep-patterns-heart-health",
    excerpt:
      "Researchers found that consistent sleep schedules were associated with lower cardiovascular risk over a decade-long study.",
    content: [
      "A long-term study tracking thousands of adults found that consistent sleep and wake times were associated with a meaningfully lower risk of cardiovascular events, independent of total sleep duration.",
      "Researchers said irregular sleep patterns appeared to disrupt metabolic and hormonal processes linked to heart health, even among participants who slept the recommended number of hours.",
      "Public health officials said the findings reinforce existing sleep guidance and may inform future preventive health recommendations.",
    ],
    categorySlug: "health",
    countryIso2: "GB",
    tagSlugs: ["public-health"],
    daysAgo: 5,
    viewCount: 2200,
    bookmarkCount: 95,
    commentCount: 11,
    isFeatured: false,
    coverSeed: "sleep-health",
  },
  {
    title: "National Team Advances to Championship Semifinals",
    slug: "national-team-advances-championship-semifinals",
    excerpt:
      "A late second-half goal secured a dramatic win and sent the squad through to the tournament's final four.",
    content: [
      "The national squad advanced to the championship semifinals after a tense match decided by a goal in the closing minutes, sparking celebrations among fans who packed venues across the country.",
      "Coaches credited a disciplined defensive performance for keeping the match close before the squad's attacking players broke through late in the second half.",
      "The team will face a tough opponent in the semifinal, with tickets for the match reportedly selling out within hours of going on sale.",
    ],
    categorySlug: "sports",
    countryIso2: "BR",
    tagSlugs: ["football"],
    daysAgo: 1,
    viewCount: 6700,
    bookmarkCount: 300,
    commentCount: 64,
    isFeatured: true,
    coverSeed: "football-semis",
  },
  {
    title: "Historic Museum Unveils Restored Masterpiece Collection",
    slug: "historic-museum-restored-masterpiece-collection",
    excerpt:
      "Years of conservation work have returned a celebrated collection to public view ahead of a landmark anniversary.",
    content: [
      "A renowned museum reopened a wing housing one of its most celebrated collections following a multi-year restoration effort led by a team of international conservators.",
      "Curators said advanced imaging techniques allowed restorers to address decades of environmental wear while preserving each work's original character.",
      "The reopening coincides with the institution's anniversary and is expected to draw large crowds throughout the coming season.",
    ],
    categorySlug: "culture",
    countryIso2: "FR",
    tagSlugs: ["cinema"],
    daysAgo: 6,
    viewCount: 1800,
    bookmarkCount: 70,
    commentCount: 8,
    isFeatured: false,
    coverSeed: "museum-collection",
  },
  {
    title: "Coastal Cities Ramp Up Climate Resilience Efforts",
    slug: "coastal-cities-climate-resilience-efforts",
    excerpt:
      "Municipal governments are investing in flood barriers, wetland restoration, and early-warning systems as sea levels rise.",
    content: [
      "Coastal municipalities announced expanded investment in flood defenses, wetland restoration, and early-warning systems as officials work to reduce the impact of rising sea levels and increasingly severe storms.",
      "Planners said nature-based approaches, including restored mangroves and wetlands, are increasingly favored alongside traditional infrastructure for their cost-effectiveness and ecological benefits.",
      "Community groups welcomed the investment but urged faster timelines, noting that several neighborhoods have already experienced repeated flooding in recent years.",
    ],
    categorySlug: "environment",
    countryIso2: "AU",
    tagSlugs: ["climate-change", "wildlife-conservation"],
    daysAgo: 4,
    viewCount: 2600,
    bookmarkCount: 110,
    commentCount: 19,
    isFeatured: false,
    coverSeed: "coastal-resilience",
  },
  {
    title: "Streaming Platforms Compete for Award-Season Spotlight",
    slug: "streaming-platforms-award-season-spotlight",
    excerpt:
      "A crowded release calendar has intensified competition among platforms vying for critical recognition this season.",
    content: [
      "Major streaming platforms rolled out a wave of high-profile releases as award season approaches, intensifying competition for critical acclaim and audience attention.",
      "Industry analysts said the crowded calendar reflects platforms' growing willingness to invest heavily in prestige productions to build brand reputation, even when box-office-style returns are uncertain.",
      "Early reviews have been mixed, with critics praising several performances while noting an increasingly saturated release schedule.",
    ],
    categorySlug: "entertainment",
    countryIso2: "US",
    tagSlugs: ["cinema"],
    daysAgo: 2,
    viewCount: 3400,
    bookmarkCount: 140,
    commentCount: 27,
    isFeatured: false,
    coverSeed: "award-season",
  },
  {
    title: "Lawmakers Debate Sweeping Electoral Reform Bill",
    slug: "lawmakers-debate-electoral-reform-bill",
    excerpt:
      "The proposed legislation would overhaul voter registration and campaign finance rules ahead of the next election cycle.",
    content: [
      "Lawmakers began formal debate on a wide-ranging electoral reform bill that would update voter registration procedures and introduce new campaign finance disclosure requirements.",
      "Supporters argued the changes would improve transparency and access to the ballot, while opponents raised concerns about implementation costs and the timeline before the next election cycle.",
      "The bill is expected to undergo several rounds of committee review before a floor vote, with debate likely to continue for weeks.",
    ],
    categorySlug: "politics",
    countryIso2: "IN",
    tagSlugs: ["elections"],
    daysAgo: 2,
    viewCount: 4700,
    bookmarkCount: 180,
    commentCount: 52,
    isFeatured: false,
    coverSeed: "electoral-reform",
  },
  {
    title: "Startup Ecosystem Sees Record Early-Stage Funding",
    slug: "startup-ecosystem-record-early-stage-funding",
    excerpt:
      "Venture investors poured record sums into early-stage companies last quarter, led by AI and clean energy startups.",
    content: [
      "Early-stage startups attracted record levels of venture funding last quarter, led by companies working in artificial intelligence and clean energy, according to a new industry report.",
      "Investors said the surge reflects renewed confidence in long-term growth sectors, even as later-stage funding rounds remain comparatively cautious.",
      "Founders described a more competitive fundraising environment, with investors moving quickly to secure stakes in promising early companies.",
    ],
    categorySlug: "business",
    countryIso2: "IN",
    tagSlugs: ["startups", "markets"],
    daysAgo: 7,
    viewCount: 1900,
    bookmarkCount: 80,
    commentCount: 12,
    isFeatured: false,
    coverSeed: "startup-funding",
  },
  {
    title: "Cybersecurity Agencies Warn of Rising Phishing Campaigns",
    slug: "cybersecurity-agencies-warn-phishing-campaigns",
    excerpt:
      "Officials say increasingly convincing phishing attempts are targeting businesses and government agencies alike.",
    content: [
      "National cybersecurity agencies issued a joint advisory warning of a sharp rise in sophisticated phishing campaigns targeting both businesses and government agencies.",
      "Officials said attackers are increasingly using convincing, well-researched messages to bypass traditional spam filters, urging organizations to strengthen employee training and multi-factor authentication.",
      "The advisory recommends regular security audits and rapid reporting of suspicious activity to limit potential damage from successful intrusions.",
    ],
    categorySlug: "technology",
    countryIso2: "DE",
    tagSlugs: ["cybersecurity"],
    daysAgo: 3,
    viewCount: 2900,
    bookmarkCount: 100,
    commentCount: 18,
    isFeatured: false,
    coverSeed: "cybersecurity-warning",
  },
  {
    title: "Space Agency Sets Date for Next Lunar Mission",
    slug: "space-agency-sets-date-lunar-mission",
    excerpt:
      "The upcoming mission will test new landing systems ahead of a planned crewed return to the lunar surface.",
    content: [
      "A national space agency confirmed the launch date for its next lunar mission, which will test new landing systems ahead of a planned crewed return to the surface in the coming years.",
      "Engineers said the uncrewed mission will carry a suite of scientific instruments alongside the landing technology demonstration, with data expected to inform future mission planning.",
      "Officials described the mission as a critical milestone in a broader program aimed at establishing a sustained lunar presence.",
    ],
    categorySlug: "science",
    countryIso2: "US",
    tagSlugs: ["space-exploration"],
    daysAgo: 8,
    viewCount: 5100,
    bookmarkCount: 260,
    commentCount: 41,
    isFeatured: true,
    coverSeed: "lunar-mission",
  },
  {
    title: "Trade Ministers Reach Framework on Cross-Border Tariffs",
    slug: "trade-ministers-framework-cross-border-tariffs",
    excerpt:
      "The preliminary agreement aims to reduce tariffs on a range of goods while easing customs procedures.",
    content: [
      "Trade ministers announced a preliminary framework agreement aimed at reducing tariffs on a range of goods while streamlining customs procedures between negotiating nations.",
      "Officials said the framework, still subject to formal ratification, is intended to lower costs for manufacturers and encourage cross-border investment.",
      "Business groups welcomed the announcement, though some sectors urged additional safeguards during the transition period.",
    ],
    categorySlug: "business",
    countryIso2: "CN",
    tagSlugs: ["global-trade", "diplomacy"],
    daysAgo: 5,
    viewCount: 2400,
    bookmarkCount: 90,
    commentCount: 16,
    isFeatured: false,
    coverSeed: "trade-framework",
  },
  {
    title: "Public Health Officials Launch Nationwide Vaccination Drive",
    slug: "officials-launch-nationwide-vaccination-drive",
    excerpt:
      "The campaign aims to expand immunization coverage in underserved rural communities over the next six months.",
    content: [
      "Health officials launched a nationwide vaccination campaign aimed at expanding immunization coverage in underserved rural communities over the next six months.",
      "The initiative includes mobile clinics and partnerships with local community organizations to reach populations with limited access to regular healthcare services.",
      "Officials said early participation figures were encouraging and pledged to publish regular progress updates throughout the campaign.",
    ],
    categorySlug: "health",
    countryIso2: "NG",
    tagSlugs: ["public-health"],
    daysAgo: 9,
    viewCount: 1700,
    bookmarkCount: 60,
    commentCount: 9,
    isFeatured: false,
    coverSeed: "vaccination-drive",
  },
  {
    title: "Host City Unveils Venues Ahead of Summer Games",
    slug: "host-city-unveils-venues-summer-games",
    excerpt:
      "Organizers showcased newly completed venues as preparations enter their final phase ahead of the summer games.",
    content: [
      "Organizers unveiled several newly completed venues as preparations for the upcoming summer games entered their final phase, with test events scheduled in the coming months.",
      "City officials said the venues were designed with post-games community use in mind, aiming to avoid the underused infrastructure that has affected past host cities.",
      "Ticket sales for marquee events are expected to open soon, with organizers anticipating strong demand.",
    ],
    categorySlug: "sports",
    countryIso2: "FR",
    tagSlugs: ["olympics"],
    daysAgo: 10,
    viewCount: 3900,
    bookmarkCount: 190,
    commentCount: 30,
    isFeatured: false,
    coverSeed: "summer-games-venues",
  },
  {
    title: "Wildlife Reserves Report Rebound in Endangered Species",
    slug: "wildlife-reserves-rebound-endangered-species",
    excerpt:
      "Conservationists credit anti-poaching measures and habitat restoration for population gains across several reserves.",
    content: [
      "Conservation officials reported a notable rebound in several endangered species populations across regional wildlife reserves, crediting expanded anti-poaching patrols and habitat restoration projects.",
      "Researchers said the gains, tracked over several years of surveys, suggest that sustained investment in conservation infrastructure can meaningfully reverse population declines.",
      "Officials cautioned that continued funding remains essential, warning that gains could be reversed without ongoing protection efforts.",
    ],
    categorySlug: "environment",
    countryIso2: "ZA",
    tagSlugs: ["wildlife-conservation"],
    daysAgo: 12,
    viewCount: 1500,
    bookmarkCount: 75,
    commentCount: 7,
    isFeatured: false,
    coverSeed: "wildlife-rebound",
  },
  {
    title: "Universities Expand Access to Online Degree Programs",
    slug: "universities-expand-access-online-degree-programs",
    excerpt:
      "A growing number of institutions are offering fully online degrees to reach students beyond traditional campuses.",
    content: [
      "A growing number of universities announced expanded online degree offerings, aiming to reach students who are unable to attend traditional in-person programs.",
      "Administrators said demand for flexible, remote-friendly education has remained strong, prompting continued investment in digital course infrastructure.",
      "Education researchers noted that outcomes for online programs have improved significantly in recent years, though they emphasized the continued importance of student support services.",
    ],
    categorySlug: "culture",
    countryIso2: "KR",
    tagSlugs: ["education"],
    daysAgo: 14,
    viewCount: 1200,
    bookmarkCount: 45,
    commentCount: 5,
    isFeatured: false,
    coverSeed: "online-degrees",
  },
  {
    title: "Central Banks Signal Coordinated Approach on Rates",
    slug: "central-banks-coordinated-approach-rates",
    excerpt:
      "Policymakers hinted at a more synchronized approach to interest rates as global growth shows signs of slowing.",
    content: [
      "Central bank officials signaled a more coordinated approach to interest rate policy as global growth indicators showed signs of slowing across several major economies.",
      "Economists said closer coordination could help reduce currency volatility, though each institution is expected to retain flexibility to respond to domestic conditions.",
      "Markets responded cautiously to the comments, with analysts awaiting further guidance at upcoming policy meetings.",
    ],
    categorySlug: "business",
    countryIso2: "GB",
    tagSlugs: ["markets", "global-trade"],
    daysAgo: 1,
    viewCount: 3600,
    bookmarkCount: 130,
    commentCount: 21,
    isFeatured: false,
    coverSeed: "central-banks",
  },
  {
    title: "Diplomats Reconvene for Fresh Round of Peace Talks",
    slug: "diplomats-reconvene-fresh-round-peace-talks",
    excerpt:
      "Negotiators returned to the table for a new round of talks aimed at de-escalating a long-running regional dispute.",
    content: [
      "Diplomats reconvened for a fresh round of negotiations aimed at de-escalating a long-running regional dispute, with mediators expressing cautious optimism about progress.",
      "Officials said the talks would focus on confidence-building measures before addressing more contentious long-term issues.",
      "Analysts described the renewed dialogue as a meaningful, if fragile, step forward after a prolonged period of limited engagement between the parties.",
    ],
    categorySlug: "politics",
    countryIso2: "JP",
    tagSlugs: ["diplomacy", "elections"],
    daysAgo: 2,
    viewCount: 4900,
    bookmarkCount: 200,
    commentCount: 45,
    isFeatured: true,
    coverSeed: "peace-talks",
  },
];
