export type CountrySeed = {
  name: string;
  iso2: string;
  iso3: string;
  region: "Africa" | "Americas" | "Asia" | "Europe" | "Oceania";
};

export const countries: CountrySeed[] = [
  // Africa
  { name: "Algeria", iso2: "DZ", iso3: "DZA", region: "Africa" },
  { name: "Angola", iso2: "AO", iso3: "AGO", region: "Africa" },
  { name: "Benin", iso2: "BJ", iso3: "BEN", region: "Africa" },
  { name: "Botswana", iso2: "BW", iso3: "BWA", region: "Africa" },
  { name: "Burkina Faso", iso2: "BF", iso3: "BFA", region: "Africa" },
  { name: "Burundi", iso2: "BI", iso3: "BDI", region: "Africa" },
  { name: "Cabo Verde", iso2: "CV", iso3: "CPV", region: "Africa" },
  { name: "Cameroon", iso2: "CM", iso3: "CMR", region: "Africa" },
  {
    name: "Central African Republic",
    iso2: "CF",
    iso3: "CAF",
    region: "Africa",
  },
  { name: "Chad", iso2: "TD", iso3: "TCD", region: "Africa" },
  { name: "Comoros", iso2: "KM", iso3: "COM", region: "Africa" },
  { name: "Congo", iso2: "CG", iso3: "COG", region: "Africa" },
  {
    name: "Congo (Democratic Republic of the)",
    iso2: "CD",
    iso3: "COD",
    region: "Africa",
  },
  { name: "Côte d'Ivoire", iso2: "CI", iso3: "CIV", region: "Africa" },
  { name: "Djibouti", iso2: "DJ", iso3: "DJI", region: "Africa" },
  { name: "Egypt", iso2: "EG", iso3: "EGY", region: "Africa" },
  { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", region: "Africa" },
  { name: "Eritrea", iso2: "ER", iso3: "ERI", region: "Africa" },
  { name: "Eswatini", iso2: "SZ", iso3: "SWZ", region: "Africa" },
  { name: "Ethiopia", iso2: "ET", iso3: "ETH", region: "Africa" },
  { name: "Gabon", iso2: "GA", iso3: "GAB", region: "Africa" },
  { name: "Gambia", iso2: "GM", iso3: "GMB", region: "Africa" },
  { name: "Ghana", iso2: "GH", iso3: "GHA", region: "Africa" },
  { name: "Guinea", iso2: "GN", iso3: "GIN", region: "Africa" },
  { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", region: "Africa" },
  { name: "Kenya", iso2: "KE", iso3: "KEN", region: "Africa" },
  { name: "Lesotho", iso2: "LS", iso3: "LSO", region: "Africa" },
  { name: "Liberia", iso2: "LR", iso3: "LBR", region: "Africa" },
  { name: "Libya", iso2: "LY", iso3: "LBY", region: "Africa" },
  { name: "Madagascar", iso2: "MG", iso3: "MDG", region: "Africa" },
  { name: "Malawi", iso2: "MW", iso3: "MWI", region: "Africa" },
  { name: "Mali", iso2: "ML", iso3: "MLI", region: "Africa" },
  { name: "Mauritania", iso2: "MR", iso3: "MRT", region: "Africa" },
  { name: "Mauritius", iso2: "MU", iso3: "MUS", region: "Africa" },
  { name: "Morocco", iso2: "MA", iso3: "MAR", region: "Africa" },
  { name: "Mozambique", iso2: "MZ", iso3: "MOZ", region: "Africa" },
  { name: "Namibia", iso2: "NA", iso3: "NAM", region: "Africa" },
  { name: "Niger", iso2: "NE", iso3: "NER", region: "Africa" },
  { name: "Nigeria", iso2: "NG", iso3: "NGA", region: "Africa" },
  { name: "Rwanda", iso2: "RW", iso3: "RWA", region: "Africa" },
  {
    name: "Sao Tome and Principe",
    iso2: "ST",
    iso3: "STP",
    region: "Africa",
  },
  { name: "Senegal", iso2: "SN", iso3: "SEN", region: "Africa" },
  { name: "Seychelles", iso2: "SC", iso3: "SYC", region: "Africa" },
  { name: "Sierra Leone", iso2: "SL", iso3: "SLE", region: "Africa" },
  { name: "Somalia", iso2: "SO", iso3: "SOM", region: "Africa" },
  { name: "South Africa", iso2: "ZA", iso3: "ZAF", region: "Africa" },
  { name: "South Sudan", iso2: "SS", iso3: "SSD", region: "Africa" },
  { name: "Sudan", iso2: "SD", iso3: "SDN", region: "Africa" },
  { name: "Tanzania", iso2: "TZ", iso3: "TZA", region: "Africa" },
  { name: "Togo", iso2: "TG", iso3: "TGO", region: "Africa" },
  { name: "Tunisia", iso2: "TN", iso3: "TUN", region: "Africa" },
  { name: "Uganda", iso2: "UG", iso3: "UGA", region: "Africa" },
  { name: "Zambia", iso2: "ZM", iso3: "ZMB", region: "Africa" },
  { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", region: "Africa" },

  // Americas
  { name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", region: "Americas" },
  { name: "Argentina", iso2: "AR", iso3: "ARG", region: "Americas" },
  { name: "Bahamas", iso2: "BS", iso3: "BHS", region: "Americas" },
  { name: "Barbados", iso2: "BB", iso3: "BRB", region: "Americas" },
  { name: "Belize", iso2: "BZ", iso3: "BLZ", region: "Americas" },
  { name: "Bolivia", iso2: "BO", iso3: "BOL", region: "Americas" },
  { name: "Brazil", iso2: "BR", iso3: "BRA", region: "Americas" },
  { name: "Canada", iso2: "CA", iso3: "CAN", region: "Americas" },
  { name: "Chile", iso2: "CL", iso3: "CHL", region: "Americas" },
  { name: "Colombia", iso2: "CO", iso3: "COL", region: "Americas" },
  { name: "Costa Rica", iso2: "CR", iso3: "CRI", region: "Americas" },
  { name: "Cuba", iso2: "CU", iso3: "CUB", region: "Americas" },
  { name: "Dominica", iso2: "DM", iso3: "DMA", region: "Americas" },
  { name: "Dominican Republic", iso2: "DO", iso3: "DOM", region: "Americas" },
  { name: "Ecuador", iso2: "EC", iso3: "ECU", region: "Americas" },
  { name: "El Salvador", iso2: "SV", iso3: "SLV", region: "Americas" },
  { name: "Grenada", iso2: "GD", iso3: "GRD", region: "Americas" },
  { name: "Guatemala", iso2: "GT", iso3: "GTM", region: "Americas" },
  { name: "Guyana", iso2: "GY", iso3: "GUY", region: "Americas" },
  { name: "Haiti", iso2: "HT", iso3: "HTI", region: "Americas" },
  { name: "Honduras", iso2: "HN", iso3: "HND", region: "Americas" },
  { name: "Jamaica", iso2: "JM", iso3: "JAM", region: "Americas" },
  { name: "Mexico", iso2: "MX", iso3: "MEX", region: "Americas" },
  { name: "Nicaragua", iso2: "NI", iso3: "NIC", region: "Americas" },
  { name: "Panama", iso2: "PA", iso3: "PAN", region: "Americas" },
  { name: "Paraguay", iso2: "PY", iso3: "PRY", region: "Americas" },
  { name: "Peru", iso2: "PE", iso3: "PER", region: "Americas" },
  {
    name: "Saint Kitts and Nevis",
    iso2: "KN",
    iso3: "KNA",
    region: "Americas",
  },
  { name: "Saint Lucia", iso2: "LC", iso3: "LCA", region: "Americas" },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "VC",
    iso3: "VCT",
    region: "Americas",
  },
  { name: "Suriname", iso2: "SR", iso3: "SUR", region: "Americas" },
  {
    name: "Trinidad and Tobago",
    iso2: "TT",
    iso3: "TTO",
    region: "Americas",
  },
  { name: "United States", iso2: "US", iso3: "USA", region: "Americas" },
  { name: "Uruguay", iso2: "UY", iso3: "URY", region: "Americas" },
  { name: "Venezuela", iso2: "VE", iso3: "VEN", region: "Americas" },

  // Asia
  { name: "Afghanistan", iso2: "AF", iso3: "AFG", region: "Asia" },
  { name: "Armenia", iso2: "AM", iso3: "ARM", region: "Asia" },
  { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", region: "Asia" },
  { name: "Bahrain", iso2: "BH", iso3: "BHR", region: "Asia" },
  { name: "Bangladesh", iso2: "BD", iso3: "BGD", region: "Asia" },
  { name: "Bhutan", iso2: "BT", iso3: "BTN", region: "Asia" },
  { name: "Brunei", iso2: "BN", iso3: "BRN", region: "Asia" },
  { name: "Cambodia", iso2: "KH", iso3: "KHM", region: "Asia" },
  { name: "China", iso2: "CN", iso3: "CHN", region: "Asia" },
  { name: "Cyprus", iso2: "CY", iso3: "CYP", region: "Asia" },
  { name: "Georgia", iso2: "GE", iso3: "GEO", region: "Asia" },
  { name: "India", iso2: "IN", iso3: "IND", region: "Asia" },
  { name: "Indonesia", iso2: "ID", iso3: "IDN", region: "Asia" },
  { name: "Iran", iso2: "IR", iso3: "IRN", region: "Asia" },
  { name: "Iraq", iso2: "IQ", iso3: "IRQ", region: "Asia" },
  { name: "Israel", iso2: "IL", iso3: "ISR", region: "Asia" },
  { name: "Japan", iso2: "JP", iso3: "JPN", region: "Asia" },
  { name: "Jordan", iso2: "JO", iso3: "JOR", region: "Asia" },
  { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", region: "Asia" },
  { name: "Kuwait", iso2: "KW", iso3: "KWT", region: "Asia" },
  { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", region: "Asia" },
  { name: "Laos", iso2: "LA", iso3: "LAO", region: "Asia" },
  { name: "Lebanon", iso2: "LB", iso3: "LBN", region: "Asia" },
  { name: "Malaysia", iso2: "MY", iso3: "MYS", region: "Asia" },
  { name: "Maldives", iso2: "MV", iso3: "MDV", region: "Asia" },
  { name: "Mongolia", iso2: "MN", iso3: "MNG", region: "Asia" },
  { name: "Myanmar", iso2: "MM", iso3: "MMR", region: "Asia" },
  { name: "Nepal", iso2: "NP", iso3: "NPL", region: "Asia" },
  { name: "North Korea", iso2: "KP", iso3: "PRK", region: "Asia" },
  { name: "Oman", iso2: "OM", iso3: "OMN", region: "Asia" },
  { name: "Pakistan", iso2: "PK", iso3: "PAK", region: "Asia" },
  { name: "Palestine", iso2: "PS", iso3: "PSE", region: "Asia" },
  { name: "Philippines", iso2: "PH", iso3: "PHL", region: "Asia" },
  { name: "Qatar", iso2: "QA", iso3: "QAT", region: "Asia" },
  { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", region: "Asia" },
  { name: "Singapore", iso2: "SG", iso3: "SGP", region: "Asia" },
  { name: "South Korea", iso2: "KR", iso3: "KOR", region: "Asia" },
  { name: "Sri Lanka", iso2: "LK", iso3: "LKA", region: "Asia" },
  { name: "Syria", iso2: "SY", iso3: "SYR", region: "Asia" },
  { name: "Taiwan", iso2: "TW", iso3: "TWN", region: "Asia" },
  { name: "Tajikistan", iso2: "TJ", iso3: "TJK", region: "Asia" },
  { name: "Thailand", iso2: "TH", iso3: "THA", region: "Asia" },
  { name: "Timor-Leste", iso2: "TL", iso3: "TLS", region: "Asia" },
  { name: "Turkey", iso2: "TR", iso3: "TUR", region: "Asia" },
  { name: "Turkmenistan", iso2: "TM", iso3: "TKM", region: "Asia" },
  { name: "United Arab Emirates", iso2: "AE", iso3: "ARE", region: "Asia" },
  { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", region: "Asia" },
  { name: "Vietnam", iso2: "VN", iso3: "VNM", region: "Asia" },
  { name: "Yemen", iso2: "YE", iso3: "YEM", region: "Asia" },

  // Europe
  { name: "Albania", iso2: "AL", iso3: "ALB", region: "Europe" },
  { name: "Andorra", iso2: "AD", iso3: "AND", region: "Europe" },
  { name: "Austria", iso2: "AT", iso3: "AUT", region: "Europe" },
  { name: "Belarus", iso2: "BY", iso3: "BLR", region: "Europe" },
  { name: "Belgium", iso2: "BE", iso3: "BEL", region: "Europe" },
  {
    name: "Bosnia and Herzegovina",
    iso2: "BA",
    iso3: "BIH",
    region: "Europe",
  },
  { name: "Bulgaria", iso2: "BG", iso3: "BGR", region: "Europe" },
  { name: "Croatia", iso2: "HR", iso3: "HRV", region: "Europe" },
  { name: "Czechia", iso2: "CZ", iso3: "CZE", region: "Europe" },
  { name: "Denmark", iso2: "DK", iso3: "DNK", region: "Europe" },
  { name: "Estonia", iso2: "EE", iso3: "EST", region: "Europe" },
  { name: "Finland", iso2: "FI", iso3: "FIN", region: "Europe" },
  { name: "France", iso2: "FR", iso3: "FRA", region: "Europe" },
  { name: "Germany", iso2: "DE", iso3: "DEU", region: "Europe" },
  { name: "Greece", iso2: "GR", iso3: "GRC", region: "Europe" },
  { name: "Hungary", iso2: "HU", iso3: "HUN", region: "Europe" },
  { name: "Iceland", iso2: "IS", iso3: "ISL", region: "Europe" },
  { name: "Ireland", iso2: "IE", iso3: "IRL", region: "Europe" },
  { name: "Italy", iso2: "IT", iso3: "ITA", region: "Europe" },
  { name: "Kosovo", iso2: "XK", iso3: "XKX", region: "Europe" },
  { name: "Latvia", iso2: "LV", iso3: "LVA", region: "Europe" },
  { name: "Liechtenstein", iso2: "LI", iso3: "LIE", region: "Europe" },
  { name: "Lithuania", iso2: "LT", iso3: "LTU", region: "Europe" },
  { name: "Luxembourg", iso2: "LU", iso3: "LUX", region: "Europe" },
  { name: "Malta", iso2: "MT", iso3: "MLT", region: "Europe" },
  { name: "Moldova", iso2: "MD", iso3: "MDA", region: "Europe" },
  { name: "Monaco", iso2: "MC", iso3: "MCO", region: "Europe" },
  { name: "Montenegro", iso2: "ME", iso3: "MNE", region: "Europe" },
  { name: "Netherlands", iso2: "NL", iso3: "NLD", region: "Europe" },
  { name: "North Macedonia", iso2: "MK", iso3: "MKD", region: "Europe" },
  { name: "Norway", iso2: "NO", iso3: "NOR", region: "Europe" },
  { name: "Poland", iso2: "PL", iso3: "POL", region: "Europe" },
  { name: "Portugal", iso2: "PT", iso3: "PRT", region: "Europe" },
  { name: "Romania", iso2: "RO", iso3: "ROU", region: "Europe" },
  { name: "Russia", iso2: "RU", iso3: "RUS", region: "Europe" },
  { name: "San Marino", iso2: "SM", iso3: "SMR", region: "Europe" },
  { name: "Serbia", iso2: "RS", iso3: "SRB", region: "Europe" },
  { name: "Slovakia", iso2: "SK", iso3: "SVK", region: "Europe" },
  { name: "Slovenia", iso2: "SI", iso3: "SVN", region: "Europe" },
  { name: "Spain", iso2: "ES", iso3: "ESP", region: "Europe" },
  { name: "Sweden", iso2: "SE", iso3: "SWE", region: "Europe" },
  { name: "Switzerland", iso2: "CH", iso3: "CHE", region: "Europe" },
  { name: "Ukraine", iso2: "UA", iso3: "UKR", region: "Europe" },
  { name: "United Kingdom", iso2: "GB", iso3: "GBR", region: "Europe" },
  { name: "Vatican City", iso2: "VA", iso3: "VAT", region: "Europe" },

  // Oceania
  { name: "Australia", iso2: "AU", iso3: "AUS", region: "Oceania" },
  { name: "Fiji", iso2: "FJ", iso3: "FJI", region: "Oceania" },
  { name: "Kiribati", iso2: "KI", iso3: "KIR", region: "Oceania" },
  { name: "Marshall Islands", iso2: "MH", iso3: "MHL", region: "Oceania" },
  { name: "Micronesia", iso2: "FM", iso3: "FSM", region: "Oceania" },
  { name: "Nauru", iso2: "NR", iso3: "NRU", region: "Oceania" },
  { name: "New Zealand", iso2: "NZ", iso3: "NZL", region: "Oceania" },
  { name: "Palau", iso2: "PW", iso3: "PLW", region: "Oceania" },
  { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", region: "Oceania" },
  { name: "Samoa", iso2: "WS", iso3: "WSM", region: "Oceania" },
  { name: "Solomon Islands", iso2: "SB", iso3: "SLB", region: "Oceania" },
  { name: "Tonga", iso2: "TO", iso3: "TON", region: "Oceania" },
  { name: "Tuvalu", iso2: "TV", iso3: "TUV", region: "Oceania" },
  { name: "Vanuatu", iso2: "VU", iso3: "VUT", region: "Oceania" },
];
